-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKmdWv5FxTHu2JLOW
V+Pj/pvyIZFddlCGv9Ai5uGfTemgCgYIKoZIzj0DAQehRANCAAQtfooMefVurN/V
Nx5xmRLaJpGlmw0wvde44XPBbX4GCX4XnW/RojxCOCxbkPOsU0sFIcI55fHUkZKw
+Z4IVrww
-----END PRIVATE KEY-----